@extends('layouts.app')
@section('title', 'Revenue by Employee — Barcoded Items')

@section('content')
<section class="content-header">
    <h1>Revenue by Employee — Barcoded Items</h1>
    <small class="text-muted">
        Sales generated by items each employee added to inventory (mass-add / barcoding flow).
    </small>
</section>

<section class="content">
    <div class="box box-primary">
        <div class="box-header with-border"><h3 class="box-title">Date Range</h3></div>
        <div class="box-body">
            <form method="GET" action="{{ action('ReportController@revenueByEmployeeBarcoding') }}" class="row">
                <div class="col-md-3">
                    <label>Start Date</label>
                    <input type="date" class="form-control" name="start_date" value="{{ $start_date }}">
                </div>
                <div class="col-md-3">
                    <label>End Date</label>
                    <input type="date" class="form-control" name="end_date" value="{{ $end_date }}">
                </div>
                <div class="col-md-3">
                    <label style="display:block;">&nbsp;</label>
                    <button type="submit" class="btn btn-primary">Apply</button>
                </div>
            </form>
            <p class="text-muted small" style="margin-top:8px;">
                Date range filters sales. <strong>Items barcoded</strong> is lifetime per employee;
                <strong>items sold</strong> and <strong>revenue</strong> are restricted to the window.
            </p>
        </div>
    </div>

    <div class="box box-solid">
        <div class="box-header with-border"><h3 class="box-title">By Employee</h3></div>
        <div class="box-body table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Employee</th>
                        <th class="text-right">Items Barcoded (lifetime)</th>
                        <th class="text-right">Items Sold (in period)</th>
                        <th class="text-right">Revenue / Item</th>
                        <th class="text-right">Total Revenue</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($rows as $r)
                        <tr>
                            <td>
                                <a href="{{ route('reports.revenue-by-employee-barcoding.detail', ['user_id' => $r->user_id, 'start_date' => $start_date, 'end_date' => $end_date]) }}">
                                    {{ $r->employee ?: ('User #' . $r->user_id) }}
                                </a>
                            </td>
                            <td class="text-right">{{ number_format($r->barcoded_count) }}</td>
                            <td class="text-right">{{ number_format($r->items_sold) }}</td>
                            <td class="text-right">${{ number_format($r->revenue_per_item, 2) }}</td>
                            <td class="text-right"><strong>${{ number_format($r->total_revenue, 2) }}</strong></td>
                        </tr>
                    @empty
                        <tr><td colspan="5" class="text-center text-muted">No data found for this range.</td></tr>
                    @endforelse
                </tbody>
                @if($rows->isNotEmpty())
                <tfoot>
                    <tr>
                        <th>Total</th>
                        <th class="text-right">{{ number_format($rows->sum('barcoded_count')) }}</th>
                        <th class="text-right">{{ number_format($rows->sum('items_sold')) }}</th>
                        <th></th>
                        <th class="text-right">${{ number_format($rows->sum('total_revenue'), 2) }}</th>
                    </tr>
                </tfoot>
                @endif
            </table>
        </div>
    </div>
</section>
@endsection
