@extends('layouts.app')
@section('title', 'Revenue by Employee — Barcoded Items')

@section('content')
<section class="content-header">
    <h1>Revenue by Employee — Barcoded Items</h1>
    <small class="text-muted">
        Sales generated by items each employee added to inventory (any creation flow).
    </small>
</section>

<section class="content">
    <div class="box box-primary">
        <div class="box-header with-border"><h3 class="box-title">Date Range</h3></div>
        <div class="box-body">
            <form method="GET" action="{{ action('ReportController@revenueByEmployeeBarcoding') }}" class="row">
                <div class="col-md-3">
                    <label>Start Date</label>
                    <input type="date" class="form-control" name="start_date" value="{{ $start_date }}">
                </div>
                <div class="col-md-3">
                    <label>End Date</label>
                    <input type="date" class="form-control" name="end_date" value="{{ $end_date }}">
                </div>
                <div class="col-md-3">
                    <label style="display:block;">&nbsp;</label>
                    <button type="submit" class="btn btn-primary">Apply</button>
                </div>
            </form>
            <p class="text-muted small" style="margin-top:8px;">
                Date range filters sales. <strong>Items barcoded</strong> and <strong>sell-through (lifetime)</strong>
                are lifetime per employee; <strong>items sold</strong> and <strong>revenue</strong> are restricted to the
                window. Lifetime sell-through can read 100% with 0 items sold in the period — all their barcoded items
                sold at some point, just not inside the selected dates. <strong>Sell-through (period)</strong> is items
                sold in the window ÷ items barcoded in the window, so it tracks the date range and can exceed 100% when
                selling down older stock.
            </p>
        </div>
    </div>

    <div class="box box-solid">
        <div class="box-header with-border"><h3 class="box-title">By Employee</h3></div>
        <div class="box-body table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Employee</th>
                        <th class="text-right">Items Barcoded (lifetime)</th>
                        <th class="text-right">Items Sold (in period)</th>
                        <th class="text-right" title="Lifetime: items sold ÷ items barcoded — ignores the date range">Sell-through (lifetime)</th>
                        <th class="text-right" title="Period: items sold in period ÷ items barcoded in period — can exceed 100% when selling older stock; “—” means nothing was barcoded in the window">Sell-through (period)</th>
                        <th class="text-right" title="Total revenue ÷ items sold">Revenue / Item Sold</th>
                        <th class="text-right" title="Total revenue ÷ items barcoded (lifetime)">Revenue / Item Listed</th>
                        <th class="text-right">Total Revenue</th>
                        <th class="text-right" title="Hours worked in selected window — Sling if connected, otherwise cash-register open/close times capped at 6h/shift">Hours Worked</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($rows as $r)
                        <tr>
                            <td>
                                <a href="{{ route('reports.revenue-by-employee-barcoding.detail', ['user_id' => $r->user_id, 'start_date' => $start_date, 'end_date' => $end_date]) }}">
                                    {{ $r->employee ?: ('User #' . $r->user_id) }}
                                </a>
                            </td>
                            <td class="text-right">{{ number_format($r->barcoded_count) }}</td>
                            <td class="text-right">{{ number_format($r->items_sold) }}</td>
                            <td class="text-right">{{ number_format($r->sell_through_pct, 1) }}%</td>
                            <td class="text-right">{{ is_null($r->sell_through_period_pct) ? '—' : number_format($r->sell_through_period_pct, 1) . '%' }}</td>
                            <td class="text-right">${{ number_format($r->revenue_per_item, 2) }}</td>
                            <td class="text-right">${{ number_format($r->revenue_per_listed_item, 2) }}</td>
                            <td class="text-right"><strong>${{ number_format($r->total_revenue, 2) }}</strong></td>
                            <td class="text-right">{{ ($r->hours_worked ?? 0) > 0 ? number_format($r->hours_worked, 1) . 'h' : '—' }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="9" class="text-center text-muted">No data found for this range.</td></tr>
                    @endforelse
                </tbody>
                @if($rows->isNotEmpty())
                <tfoot>
                    @php
                        $tot_bar = $rows->sum('barcoded_count');
                        $tot_life_sold = $rows->sum('lifetime_items_sold');
                        $overall_st = $tot_bar > 0 ? ($tot_life_sold / $tot_bar) * 100 : 0;
                        $tot_bar_period = $rows->sum('barcoded_period');
                        $tot_sold_period = $rows->sum('items_sold');
                        $overall_st_period = $tot_bar_period > 0 ? ($tot_sold_period / $tot_bar_period) * 100 : null;
                    @endphp
                    <tr>
                        <th>Total</th>
                        <th class="text-right">{{ number_format($tot_bar) }}</th>
                        <th class="text-right">{{ number_format($rows->sum('items_sold')) }}</th>
                        <th class="text-right">{{ number_format($overall_st, 1) }}%</th>
                        <th class="text-right">{{ is_null($overall_st_period) ? '—' : number_format($overall_st_period, 1) . '%' }}</th>
                        <th></th>
                        <th></th>
                        <th class="text-right">${{ number_format($rows->sum('total_revenue'), 2) }}</th>
                        <th class="text-right">{{ number_format($rows->sum('hours_worked'), 1) }}h</th>
                    </tr>
                </tfoot>
                @endif
            </table>
        </div>
    </div>
</section>
@endsection
