@extends('layouts.app')

@section('title', 'TikTok API Settings')

@section('content')
@include('sale_pos.partials._redesign_v2')
<script>document.body.classList.add('pos-v2');</script>

<style>
body.pos-v2 .quo-wrap { max-width: 760px; margin: 0 auto; padding: 18px 16px 60px; font-family: "Inter Tight", system-ui, sans-serif; color: var(--pos-ink); }
body.pos-v2 .quo-wrap h1 { font-size: 24px; font-weight: 700; margin: 0 0 4px; }
body.pos-v2 .quo-wrap .sub { color: #6b6253; margin: 0 0 20px; font-size: 14px; }
body.pos-v2 .quo-card { background: var(--pos-surface); border: 1px solid var(--pos-line); border-radius: 14px; padding: 20px 22px; margin-bottom: 16px; }
body.pos-v2 .quo-card h3 { font-size: 15px; font-weight: 700; margin: 0 0 8px; }
body.pos-v2 .quo-card p { font-size: 13.5px; color: #6b6253; margin: 0 0 12px; }
body.pos-v2 label { font-weight: 600; font-size: 13px; }
body.pos-v2 .form-control { border: 1px solid var(--pos-line-2); border-radius: 8px; padding: 9px 11px; font-family: "IBM Plex Mono", monospace; font-size: 13px; margin-bottom: 10px; }
body.pos-v2 .btn-accent { background: var(--pos-accent); color: var(--pos-accent-text); border: 1px solid var(--pos-accent-deep);
  border-radius: 10px; padding: 9px 16px; font-weight: 700; font-size: 14px; cursor: pointer; font-family: "Inter Tight", sans-serif; margin-top: 4px; }
body.pos-v2 .btn-accent:hover { background: var(--pos-accent-deep); color: var(--pos-accent-text); }
body.pos-v2 .status-line { font-size: 12.5px; color: #8a8070; margin-bottom: 10px; }
</style>

<div class="quo-wrap">
    <h1>TikTok API Settings</h1>
    <p class="sub">Powers the live TikTok followers/likes/video numbers on the Archer performance report. Uses a TikTok for Developers app in Sandbox mode against the Nivessa account added as a target user &mdash; no App Review needed for our own account.</p>

    @if(is_array(session('status')))
        <div class="alert {{ session('status')['success'] ? 'alert-success' : 'alert-danger' }}">{{ session('status')['msg'] }}</div>
    @endif

    <div class="quo-card">
        <h3>Credentials</h3>
        <p>From the app's Sandbox at developers.tiktok.com &mdash; Client key/secret from Credentials, access/refresh token from completing the Login Kit OAuth flow for the @nivessarecords target account.</p>
        <form method="POST" action="{{ action('TiktokAuthController@saveSettings') }}">
            @csrf
            <label>Client key</label>
            <input type="text" name="client_key" class="form-control" style="width:100%;" value="{{ $client_key }}" placeholder="paste here">

            <label>Client secret</label>
            <input type="text" name="client_secret" class="form-control" style="width:100%;" placeholder="paste here">
            <div class="status-line">{{ $client_secret_masked ? 'Currently set, ending in ' . $client_secret_masked : 'Not set yet.' }}</div>

            <label>Access token</label>
            <input type="text" name="access_token" class="form-control" style="width:100%;" placeholder="paste here">
            <div class="status-line">{{ $access_token_masked ? 'Currently set, ending in ' . $access_token_masked : 'Not set yet.' }}</div>

            <label>Refresh token</label>
            <input type="text" name="refresh_token" class="form-control" style="width:100%;" placeholder="paste here">
            <div class="status-line">{{ $refresh_token_masked ? 'Currently set, ending in ' . $refresh_token_masked : 'Not set yet.' }}</div>

            <label>Access token expires at (unix timestamp)</label>
            <input type="text" name="expires_at" class="form-control" style="width:100%;" placeholder="e.g. 1758838800">
            <div class="status-line">{{ $expires_at ? 'Currently expires ' . $expires_at : 'Not set yet.' }}</div>

            <button type="submit" class="btn-accent">Save</button>
        </form>
    </div>

    <div class="quo-card">
        <h3>Note on token expiry</h3>
        <p>Access tokens last 24 hours; the report auto-refreshes using the stored refresh token (valid ~1 year) and saves the new pair here automatically. If the numbers ever silently go stale, the refresh token itself may need to be regenerated by redoing the OAuth flow.</p>
    </div>
</div>

@stop
